[package]
name = "analyzer"
version = "0.1.0"
authors = ["Njagi Mwaniki <njagi@urbanslug.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf = "0.6.3"
pdf-extract = "0.6.1"
lopdf = "0.23.0"

getopts = "0.2"